---
- hosts: servers
  gather_facts: yes
  become: yes

  vars:
    home_dir: "/home/{{ ansible_user }}"

  handlers:
    - name: reboot
      reboot:

  roles:
    - role: prerequisites
    - role: samba
    - role: development
    - role: streaming/development
    - role: streaming/kafka
    - role: streaming/spark
    - role: streaming/mariadb
    - role: streaming/superset
    - role: postrequisites