---
# DEVELOPMENT #
###################################################################################################################  
## ARCHICONDA
- name: check if conda binary is present
  stat: path={{ home_dir }}/archiconda3/bin/conda
  register: conda

- name: Download Archiconda3
  get_url:
    url: https://github.com/Archiconda/build-tools/releases/download/0.2.3/Archiconda3-0.2.3-Linux-aarch64.sh
    dest: "{{ home_dir }}/tmp/Archiconda3-0.2.3-Linux-aarch64.sh"
    mode: '755'
  when: conda.stat.exists == False

- name: install Archiconda3
  expect:
    command: "{{ home_dir }}/tmp/Archiconda3-0.2.3-Linux-aarch64.sh"
    responses:
        'continue': '\n'
        '27': 'yes'
        'bashrc': 'no'
        'below': '{{ home_dir }}/archiconda3'
    echo: true
  when: conda.stat.exists == False
  no_log: false

- name: set "{{ ansible_user }}" as owner
  file: 
    dest: "{{ home_dir }}/archiconda3"
    owner: "{{ ansible_user }}" 
    group: "{{ ansible_user }}" 
    recurse: yes
  notify: reboot

- name: update Archiconda3
  command: "{{ home_dir }}/archiconda3/bin/conda update -y --all"

- name: add archiconda binary to path
  lineinfile:
    dest: "{{ home_dir }}/.bashrc"
    line: ". {{ home_dir }}/archiconda3/etc/profile.d/conda.sh"